pipeline {
    agent any

    stages {
        // stage('Build') {
        //     steps {
        //          dir('axe-testing') {
        //             script{
        //                 sh '''
        //                     echo 'Building...'
        //                 '''
        //                 // npm install && npm run build
        //             }
        //         }
        //     }
        // }

        stage('Test') {
            steps {
                // dir('axe-testing') {
                    script{
                        sh '''
                            echo "Testing..."
                            mvn clean test -Dheadless=true 
                        '''
                    }
                    // npm install && npm run build

                    // withSonarQubeEnv('SonarCloud') {
                    //     sh '''
                    //         npx sonar-scanner \
                    //         -Dsonar.projectKey=maelstromdef_warehousemanager-frontend \
                    //         -Dsonar.projectName=warehousemanager-frontend \
                    //         -Dsonar.sources=src \
                    //         -Dsonar.exclusions=**/__tests__/**,src/test/** \
                            
                    //     '''
                    // }
                // }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }

        stage('Succussful Run') {
            steps {
                echo 'SUCCESS!'
            }
        }
    }
}