pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script{
                    dir('web-x-testing') {
                        sh '''
                            echo 'Building...'
                            npm install && npm run build       
                        '''
                        // npm install && npm run build
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script{
                    dir('web-x-testing') {
                        sh '''
                            echo "Testing..."
                            ls -al       
                        '''
                        // npm install && npm run build

                        // withSonarQubeEnv('SonarCloud') {
                        //     sh '''
                        //         npx sonar-scanner \
                        //         -Dsonar.projectKey=maelstromdef_warehousemanager-frontend \
                        //         -Dsonar.projectName=warehousemanager-frontend \
                        //         -Dsonar.sources=src \
                        //         -Dsonar.exclusions=**/__tests__/**,src/test/** \
                                
                        //     '''
                        // }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }

        stage('Succussful Run') {
            steps {
                echo 'SUCCESS!'
            }
        }
    }
}